<?php

/**
 * This is the model base class for the table "obk_items".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ObkItems".
 *
 * Columns in table "obk_items" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $category_id
 * @property string $name
 * @property integer $repa_cost
 * @property double $cost
 * @property integer $nlevel
 * @property integer $nsila
 * @property integer $nlovk
 * @property integer $ninta
 * @property integer $nvinos
 * @property integer $nnoj
 * @property integer $ntopor
 * @property integer $nmech
 * @property integer $ndubina
 * @property string $nalign
 * @property integer $minu
 * @property integer $maxu
 * @property integer $gsila
 * @property integer $glovk
 * @property integer $ginta
 * @property integer $gintel
 * @property integer $gmudra
 * @property integer $ghp
 * @property integer $mfkrit
 * @property integer $mfakrit
 * @property integer $mfuvorot
 * @property integer $mfauvorot
 * @property integer $gnoj
 * @property integer $gtopor
 * @property integer $gdubina
 * @property integer $gmech
 * @property string $img
 * @property integer $bron1
 * @property integer $bron2
 * @property integer $bron3
 * @property integer $bron4
 * @property integer $massa
 * @property integer $freestats
 * @property integer $freemf
 * @property integer $usil_uron
 * @property integer $usil_bron
 * @property integer $usil_max_mf
 * @property integer $is_art
 * @property integer $can_mf
 * @property integer $can_ap
 * @property integer $can_podgon
 *
 * @property integer $need_fire
 * @property integer $need_water
 * @property integer $need_air
 * @property integer $need_earth
 * @property integer $need_light
 * @property integer $need_gray
 * @property integer $need_dark
 * @property integer $give_fire
 * @property integer $give_water
 * @property integer $give_air
 * @property integer $give_earth
 * @property integer $give_light
 * @property integer $give_gray
 * @property integer $give_dark
 *
 * @property integer $rareitem
 * @property integer $can_rep
 *
 */
abstract class BaseObkItems extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'obk_items';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ObkItems|ObkItems', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('category_id, name, repa_cost, cost, nlevel, nsila, nlovk, ninta, nvinos, nnoj, ntopor, nmech, ndubina, nalign, minu, maxu, gsila, glovk, ginta, gintel, gmudra, ghp, mfkrit, mfakrit, mfuvorot, mfauvorot, gnoj, gtopor, gdubina, gmech, img, bron1, bron2, bron3, bron4, massa, usil_uron, usil_bron, usil_max_mf', 'required'),
			array('category_id, repa_cost, nlevel, nsila, nlovk, ninta, nvinos, nnoj, ntopor, nmech, ndubina, minu, maxu, gsila, glovk, ginta, gintel, gmudra, ghp, mfkrit, mfakrit, mfuvorot, mfauvorot, gnoj, gtopor, gdubina, gmech, bron1, bron2, bron3, bron4, massa, freestats, freemf, usil_uron, usil_bron, usil_max_mf, is_art, can_mf, can_ap, can_podgon', 'numerical', 'integerOnly'=>true),
			array('cost', 'numerical'),
			array('name, nalign, img', 'length', 'max'=>255),
			array('freestats, freemf, is_art, can_mf, can_ap, can_podgon', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, category_id, name, repa_cost, cost, nlevel, nsila, nlovk, ninta, nvinos, nnoj, ntopor, nmech, ndubina, nalign, minu, maxu, gsila, glovk, ginta, gintel, gmudra, ghp, mfkrit, mfakrit, mfuvorot, mfauvorot, gnoj, gtopor, gdubina, gmech, img, bron1, bron2, bron3, bron4, massa, freestats, freemf, usil_uron, usil_bron, usil_max_mf, is_art, can_mf, can_ap, can_podgon', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'category_id' => Yii::t('app', 'Category'),
			'name' => Yii::t('app', 'Name'),
			'repa_cost' => Yii::t('app', 'Repa Cost'),
			'cost' => Yii::t('app', 'Cost'),
			'nlevel' => Yii::t('app', 'Nlevel'),
			'nsila' => Yii::t('app', 'Nsila'),
			'nlovk' => Yii::t('app', 'Nlovk'),
			'ninta' => Yii::t('app', 'Ninta'),
			'nvinos' => Yii::t('app', 'Nvinos'),
			'nnoj' => Yii::t('app', 'Nnoj'),
			'ntopor' => Yii::t('app', 'Ntopor'),
			'nmech' => Yii::t('app', 'Nmech'),
			'ndubina' => Yii::t('app', 'Ndubina'),
			'nalign' => Yii::t('app', 'Nalign'),
			'minu' => Yii::t('app', 'Minu'),
			'maxu' => Yii::t('app', 'Maxu'),
			'gsila' => Yii::t('app', 'Gsila'),
			'glovk' => Yii::t('app', 'Glovk'),
			'ginta' => Yii::t('app', 'Ginta'),
			'gintel' => Yii::t('app', 'Gintel'),
			'gmudra' => Yii::t('app', 'Gmudra'),
			'ghp' => Yii::t('app', 'Ghp'),
			'mfkrit' => Yii::t('app', 'Mfkrit'),
			'mfakrit' => Yii::t('app', 'Mfakrit'),
			'mfuvorot' => Yii::t('app', 'Mfuvorot'),
			'mfauvorot' => Yii::t('app', 'Mfauvorot'),
			'gnoj' => Yii::t('app', 'Gnoj'),
			'gtopor' => Yii::t('app', 'Gtopor'),
			'gdubina' => Yii::t('app', 'Gdubina'),
			'gmech' => Yii::t('app', 'Gmech'),
			'img' => Yii::t('app', 'Img'),
			'bron1' => Yii::t('app', 'Bron1'),
			'bron2' => Yii::t('app', 'Bron2'),
			'bron3' => Yii::t('app', 'Bron3'),
			'bron4' => Yii::t('app', 'Bron4'),
			'massa' => Yii::t('app', 'Massa'),
			'freestats' => Yii::t('app', 'Freestats'),
			'freemf' => Yii::t('app', 'Freemf'),
			'usil_uron' => Yii::t('app', 'Usil Uron'),
			'usil_bron' => Yii::t('app', 'Usil Bron'),
			'usil_max_mf' => Yii::t('app', 'Usil Max Mf'),
			'is_art' => Yii::t('app', 'Is Art'),
			'can_mf' => Yii::t('app', 'Can Mf'),
			'can_ap' => Yii::t('app', 'Can Ap'),
			'can_podgon' => Yii::t('app', 'Can Podgon'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('category_id', $this->category_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('repa_cost', $this->repa_cost);
		$criteria->compare('cost', $this->cost);
		$criteria->compare('nlevel', $this->nlevel);
		$criteria->compare('nsila', $this->nsila);
		$criteria->compare('nlovk', $this->nlovk);
		$criteria->compare('ninta', $this->ninta);
		$criteria->compare('nvinos', $this->nvinos);
		$criteria->compare('nnoj', $this->nnoj);
		$criteria->compare('ntopor', $this->ntopor);
		$criteria->compare('nmech', $this->nmech);
		$criteria->compare('ndubina', $this->ndubina);
		$criteria->compare('nalign', $this->nalign, true);
		$criteria->compare('minu', $this->minu);
		$criteria->compare('maxu', $this->maxu);
		$criteria->compare('gsila', $this->gsila);
		$criteria->compare('glovk', $this->glovk);
		$criteria->compare('ginta', $this->ginta);
		$criteria->compare('gintel', $this->gintel);
		$criteria->compare('gmudra', $this->gmudra);
		$criteria->compare('ghp', $this->ghp);
		$criteria->compare('mfkrit', $this->mfkrit);
		$criteria->compare('mfakrit', $this->mfakrit);
		$criteria->compare('mfuvorot', $this->mfuvorot);
		$criteria->compare('mfauvorot', $this->mfauvorot);
		$criteria->compare('gnoj', $this->gnoj);
		$criteria->compare('gtopor', $this->gtopor);
		$criteria->compare('gdubina', $this->gdubina);
		$criteria->compare('gmech', $this->gmech);
		$criteria->compare('img', $this->img, true);
		$criteria->compare('bron1', $this->bron1);
		$criteria->compare('bron2', $this->bron2);
		$criteria->compare('bron3', $this->bron3);
		$criteria->compare('bron4', $this->bron4);
		$criteria->compare('massa', $this->massa);
		$criteria->compare('freestats', $this->freestats);
		$criteria->compare('freemf', $this->freemf);
		$criteria->compare('usil_uron', $this->usil_uron);
		$criteria->compare('usil_bron', $this->usil_bron);
		$criteria->compare('usil_max_mf', $this->usil_max_mf);
		$criteria->compare('is_art', $this->is_art);
		$criteria->compare('can_mf', $this->can_mf);
		$criteria->compare('can_ap', $this->can_ap);
		$criteria->compare('can_podgon', $this->can_podgon);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}