<?php

/**
 * This is the model base class for the table "moder".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Moder".
 *
 * Columns in table "moder" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $login
 *
 */
abstract class BaseModer extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'moder';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Moder|Moders', $n);
	}

	public static function representingColumn() {
		return 'login';
	}

	public function rules() {
		return array(
			array('login', 'required'),
			array('login', 'length', 'max'=>255),
			array('id, login', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'login' => Yii::t('app', 'Login'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('login', $this->login, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}