<?php

/**
 * This is the model base class for the table "dressroom".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Dressroom".
 *
 * Columns in table "dressroom" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $key
 * @property string $dressed
 * @property string $params
 * @property string $time
 *
 */
abstract class BaseDressroom extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'dressroom';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Dressroom|Dressrooms', $n);
	}

	public static function representingColumn() {
		return 'key';
	}

	public function rules() {
		return array(
			array('key', 'required'),
			array('dressed, params', 'safe'),
			array('dressed, params', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, key, dressed, params, time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'key' => Yii::t('app', 'Key'),
			'dressed' => Yii::t('app', 'Dressed'),
			'params' => Yii::t('app', 'Params'),
			'time' => Yii::t('app', 'Time'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('key', $this->key, true);
		$criteria->compare('dressed', $this->dressed, true);
		$criteria->compare('params', $this->params, true);
		$criteria->compare('time', $this->time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}