<div class="tab_content">
<h1><?php echo Yii::t('app', 'Просмотр') . ' ' . GxHtml::encode(GxHtml::valueEx($model)); ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data' => $model,
	'attributes' => array(
'id',
'category_id',
'name',
'price_reputation',
'price',
'price_ekr',
'durability',
'need_level',
'need_strange',
'need_agility',
'need_intuition',
'need_endurance',
'need_knife',
'need_ax',
'need_sword',
'need_baton',
'need_align',
'min_damage',
'max_damage',
'give_strange',
'give_agility',
'give_intuition',
'give_intellect',
'give_wisdom',
'give_hp',
'mf_critical',
'mf_p_critical',
'mf_flee',
'mf_p_flee',
'give_knife',
'give_ax',
'give_baton',
'give_sword',
'img',
'armor_head',
'armor_body',
'armor_belt',
'armor_feet',
'weight',
'free_stats',
'free_mf',
'increased_damage',
'increased_armor',
'increased_mf',
'is_art:boolean',
'can_mf:boolean',
'can_ap:boolean',
'can_podgon:boolean',
'enabled_rune_increased_damage:boolean',
'enabled_rune_increased_armor:boolean',
'enabled_rune_increased_mf:boolean',
'exp',
'prokat_level',
	),
)); ?>

</div>