var apImg = {
    1:baseUrl+'/images/dress/ap/up7.gif',
    2:baseUrl+'/images/dress/ap/up8.gif',
    3:baseUrl+'/images/dress/ap/up9.gif',
    4:baseUrl+'/images/dress/ap/up10.gif',
    5:baseUrl+'/images/dress/ap/up11.gif'
}
var apInfo = {
    1:{
        level:7,
        minu:1,
        maxu:1,
        hp:6,
        bron:1,
        stat:1,
        mf:5,
        iznos:5
    },
    2:{
        level:8,
        minu:2,
        maxu:2,
        hp:8,
        bron:1,
        stat:1,
        mf:7,
        iznos:5
    },
    3:{
        level:9,
        minu:3,
        maxu:3,
        hp:10,
        bron:1,
        stat:1,
        mf:10,
        iznos:10
    },
    4:{
        level:10,
        minu:4,
        maxu:4,
        hp:12,
        bron:1,
        stat:1,
        mf:12,
        iznos:10
    },
    5:{
        level:11,
        minu:1,
        maxu:1,
        hp:15,
        bron:1,
        stat:1,
        mf:15,
        iznos:15
    }
};