var empty = {
    br:baseUrl+'/images/dress/empty/w4.gif',
    ser:baseUrl+'/images/dress/empty/w1.gif',
    kl:baseUrl+'/images/dress/empty/w2.gif',
    or:baseUrl+'/images/dress/empty/w3.gif',
    nog:baseUrl+'/images/dress/empty/w3.gif',
    dubina:baseUrl+'/images/dress/empty/w3.gif',
    topor:baseUrl+'/images/dress/empty/w3.gif',
    mech:baseUrl+'/images/dress/empty/w3.gif',
    r1:baseUrl+'/images/dress/empty/w6.gif',
    r2:baseUrl+'/images/dress/empty/w6.gif',
    r3:baseUrl+'/images/dress/empty/w6.gif',
    sh:baseUrl+'/images/dress/empty/w9.gif',
    pr:baseUrl+'/images/dress/empty/w11.gif',
    st:baseUrl+'/images/dress/empty/w10.gif',
    ob:baseUrl+'/images/dress/empty/w12.gif',
    fb:baseUrl+'/images/dress/empty/empty_shirt.gif',
    pl:baseUrl+'/images/dress/empty/empty_cloack.gif'
}