var podgonInfo = {
    1:{
        mf:2,
        cost:0.2
    },
    2:{
        mf:3,
        cost:0.2
    },
    3:{
        mf:4,
        cost:0.4
    },
    4:{
        mf:6,
        cost:0.7
    },
    5:{
        mf:10,
        cost:0.1
    }
}
var podgon = {
    br:{
        1:baseUrl+'/images/dress/podgon/armor_1.gif',
        2:baseUrl+'/images/dress/podgon/armor_2.gif',
        3:baseUrl+'/images/dress/podgon/armor_3.gif',
        4:baseUrl+'/images/dress/podgon/armor_4.gif',
        5:baseUrl+'/images/dress/podgon/armor_5.gif'
    },
    ser:{
        1:baseUrl+'/images/dress/podgon/earrings_1.gif',
        2:baseUrl+'/images/dress/podgon/earrings_2.gif',
        3:baseUrl+'/images/dress/podgon/earrings_3.gif',
        4:baseUrl+'/images/dress/podgon/earrings_4.gif',
        5:baseUrl+'/images/dress/podgon/earrings_5.gif'
    },
    pr:{
        1:baseUrl+'/images/dress/podgon/gloves_1.gif',
        2:baseUrl+'/images/dress/podgon/gloves_2.gif',
        3:baseUrl+'/images/dress/podgon/gloves_3.gif',
        4:baseUrl+'/images/dress/podgon/gloves_4.gif',
        5:baseUrl+'/images/dress/podgon/gloves_5.gif'
    },
    sh:{
        1:baseUrl+'/images/dress/podgon/helmet_1.gif',
        2:baseUrl+'/images/dress/podgon/helmet_2.gif',
        3:baseUrl+'/images/dress/podgon/helmet_3.gif',
        4:baseUrl+'/images/dress/podgon/helmet_4.gif',
        5:baseUrl+'/images/dress/podgon/helmet_5.gif'
    },
    kl:{
        1:baseUrl+'/images/dress/podgon/necklace_1.gif',
        2:baseUrl+'/images/dress/podgon/necklace_2.gif',
        3:baseUrl+'/images/dress/podgon/necklace_3.gif',
        4:baseUrl+'/images/dress/podgon/necklace_4.gif',
        5:baseUrl+'/images/dress/podgon/necklace_5.gif'
    },
    r1:{
        1:baseUrl+'/images/dress/podgon/ring_1.gif',
        2:baseUrl+'/images/dress/podgon/ring_2.gif',
        3:baseUrl+'/images/dress/podgon/ring_3.gif',
        4:baseUrl+'/images/dress/podgon/ring_4.gif',
        5:baseUrl+'/images/dress/podgon/ring_5.gif'
    },
    r2:{
        1:baseUrl+'/images/dress/podgon/ring_1.gif',
        2:baseUrl+'/images/dress/podgon/ring_2.gif',
        3:baseUrl+'/images/dress/podgon/ring_3.gif',
        4:baseUrl+'/images/dress/podgon/ring_4.gif',
        5:baseUrl+'/images/dress/podgon/ring_5.gif'
    },
    r3:{
        1:baseUrl+'/images/dress/podgon/ring_1.gif',
        2:baseUrl+'/images/dress/podgon/ring_2.gif',
        3:baseUrl+'/images/dress/podgon/ring_3.gif',
        4:baseUrl+'/images/dress/podgon/ring_4.gif',
        5:baseUrl+'/images/dress/podgon/ring_5.gif'
    },
    st:{
        1:baseUrl+'/images/dress/podgon/shield_1.gif',
        2:baseUrl+'/images/dress/podgon/shield_2.gif',
        3:baseUrl+'/images/dress/podgon/shield_3.gif',
        4:baseUrl+'/images/dress/podgon/shield_4.gif',
        5:baseUrl+'/images/dress/podgon/shield_5.gif'
    },
    ob:{
        1:baseUrl+'/images/dress/podgon/shoes_1.gif',
        2:baseUrl+'/images/dress/podgon/shoes_2.gif',
        3:baseUrl+'/images/dress/podgon/shoes_3.gif',
        4:baseUrl+'/images/dress/podgon/shoes_4.gif',
        5:baseUrl+'/images/dress/podgon/shoes_5.gif'
    }
};